FROM alpine:3.7

LABEL maintainer="Julien DEL PICCOLO <julien@del-piccolo.com>"

RUN apk update \
 && apk add --no-cache ca-certificates curl \
 && apk upgrade \
 && rm -rf /var/cache/apk/* \
 && adduser -D user
 
USER user

WORKDIR /home/user

HEALTHCHECK NONE